### ISSUE TITLE
Missing CSS

### ISSUE THREAD

**Issue by lan0** [aexmachina/ember-notify#100]
Since 5.1.3 the CSS for the positioning seems to be missing.

Was the removal of this intentional? https://github.com/aexmachina/ember-notify/commit/3025cb86e6975fd755b73e53dca2861c9be40ab8#diff-168726dbe96b3ce427e7fedce31bb0bcL7

**Comment by aexmachina** [comment]
No, it wasn't. That was from a PR. Have fixed in v5.1.5, thanks for letting me know.
