### ISSUE TITLE
Ember Notify 5.1.7 w/ Ember 2.9.1

### ISSUE THREAD

**Issue by rstudner** [aexmachina/ember-notify#102]
in a component:
```
import Notify from 'ember-notify';
.
.
.
        console.log(Notify);
        Notify.success('Successfully add bar to foo');
```

output is:
function {subclass of Ember.Service}
Uncaught TypeError: _emberNotify.default.success is not a function(…)

(happens with .info etc too)

**Comment by aexmachina** [comment]
That's not the usage. See the [usage](https://github.com/aexmachina/ember-notify#usage) in the README.

**Comment by rstudner** [comment]
@aexmachina - Ahh, I was on your demo site, which had the usage above that wasn't working.
http://simonwade.me/ember-notify

**Comment by aexmachina** [comment]
Right I see, thanks for pointing it out. I should probably remove them, too hard to keep up to date!

**Comment by rstudner** [comment]
Is a brilliant add-on - thank you!
