### ISSUE TITLE
Close method?

### ISSUE THREAD

**Issue by jakeleboeuf** [aexmachina/ember-notify#108]
Is a close method available?

I'd like to have a message `saving...` and then when a promise resolves, flip the message to `saved!`. OR, I'm fine with a `saving...`, and then I'll close it when the promise resolves and fire a new message.

**Comment by jakeleboeuf** [comment]
Ahhhh I found it. Maybe not the most obvious solution, but it's there!!

```
let saving = = notify.alert('saving', {
  closeAfter: null
});

this.get('model').save().then(() => {
  saving.set('visible', false);
  this.get('notify').success('Saved successfully!');
});
```

**Comment by aexmachina** [comment]
Yep, that's it.

**Comment by gvocale** [comment]
Is there a way to specify an action to fire after closing each notification?

I.e.:
```
this.notify.success('Saved successfully', { close: this.actionToFire })
```
