### ISSUE TITLE
Support for ember-cli: 2.16.2 -  unknown injection: 'service:notify'"

### ISSUE THREAD

**Issue by lypborges** [aexmachina/ember-notify#111]
First, thank for this addon. Maybe I'm doing something wrong. 
I'm use it with ember-cli 2.16.2, but can't figure out how to inject the service from one controller

```javascript
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';

export default Controller.extend({
  notify: service('notify'),
  
});
```

> router.js:938 Error while processing route: auth.login Assertion Failed: Attempting to inject an unknown injection: 'service:notify' Error: Assertion Failed: Attempting to inject an unknown injection: 'service:notify'

I also tried to make a initializer for all controller:

```javascript
export function initialize(application) {
  application.inject('route', 'notify', 'service:notify');
  application.inject('controller', 'notify', 'service:notify');
}

export default {
  name: 'notifications',
  initialize: initialize
};
```
> EmberError {stack: "Error: Assertion Failed: Attempting to inject an u…(http://localhost:4200/assets/vendor.js:31610:14)", description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: Attempting to inject an unknown injection: 'service:notify'", …}
code
:
undefined
description
:
undefined
fileName
:
undefined
lineNumber
:
undefined
message
:
"Assertion Failed: Attempting to inject an unknown injection: 'service:notify'"
name
:
"Error"
number
:
undefined
stack
:
"Error: Assertion Failed: Attempting to inject an unknown injection: 'service:notify'↵    at new EmberError (http://localhost:4200/assets/vendor.js:35209:25)↵    at assert (http://localhost:4200/assets/vendor.js:35452:15)↵    at Registry.validateInjections (http://localhost:4200/assets/vendor.js:32327:66)↵    at buildInjections (http://localhost:4200/assets/vendor.js:31830:28)↵    at injectionsFor (http://localhost:4200/assets/vendor.js:31855:22)↵    at FactoryManager.create (http://localhost:4200/assets/vendor.js:31919:22)↵    at Proxy.create (http://localhost:4200/assets/vendor.js:31703:20)↵    at instantiateFactory (http://localhost:4200/assets/vendor.js:31791:57)↵    at lookup (http://localhost:4200/assets/vendor.js:31748:12)↵    at Container.lookup (http://localhost:4200/assets/vendor.js:31610:14)"
__proto__
:
ExtendableBuiltin
`

**Comment by lypborges** [comment]
It was a error in my app. Sorry for the issue.

**Comment by aexmachina** [comment]
Okay. You should close the issue if it's resolved.
