### ISSUE TITLE
Notify not showing on mobile

### ISSUE THREAD

**Issue by justinboohan** [aexmachina/ember-notify#112]
This is a wonderful addon, really great to use. The only problem I can see is that if I'm at the top of the screen on android the notification message doesn't show as it's tied to the bottom. Can it be tied to the bottom of the viewport rather than the bottom of the page?
Is there a css workaround for this?

**Comment by aexmachina** [comment]
That doesn't happen for me. I suspect it's something in your CSS. You can use the [demo page](http://simonwade.me/assets/ember-demos/#/ember-notify) to see for yourself (use the inspector to make the `fieldset` `height: 100vh`). Feel free to reopen if necessary.
