### ISSUE TITLE
Consider transferring to `adopted-ember-addons`

### ISSUE THREAD

**Issue by btecu** [aexmachina/ember-notify#129]
@aexmachina since there's not much _official_ activity here, would you consider the addon to the `adopted-ember-addons`? That way the community can keep the addon updated.

https://github.com/adopted-ember-addons/program-guidelines

**Comment by aexmachina** [comment]
I'd be happy to do this, but having a hard time finding the time. If you wanted to prepare the PR to move it, I'm happy to merge it and transfer ownership
