### ISSUE TITLE
Notify container is not attached to test container

### ISSUE THREAD

**Issue by joostdevries** [aexmachina/ember-notify#18]
The container for the notifications is not rendered within the testing container. Because of this, notifications are not removed after a test completes.

ember-cli 0.1.1

vendor.js:28481 DEBUG: Ember      : 1.8.0-beta.4
vendor.js:28481 DEBUG: Ember Data : 1.0.0-beta.11
vendor.js:28481 DEBUG: Handlebars : 1.3.0
vendor.js:28481 DEBUG: jQuery     : 1.11.1

**Comment by aexmachina** [comment]
This is resolved in v3.0.
