### ISSUE TITLE
Allow to register as a service

### ISSUE THREAD

**Issue by knownasilya** [aexmachina/ember-notify#21]
Have inject locations specifiable in the configuration, so `['controller', 'route:application']` will insert a `notify` object into all controllers and the ApplicationRoute, for example.

Can be used with `this.notify.info('Hey there.');`

**Comment by btecu** [comment]
Is this part of version 3?

**Comment by aexmachina** [comment]
No, but thanks for reminding me. I'll do that tonight.

**Comment by aexmachina** [comment]
This has been added v3.0.5
