### ISSUE TITLE
Removal of Notify.useBootstrap()

### ISSUE THREAD

**Issue by jcope2013** [aexmachina/ember-notify#25]
seems that is no longer available as a global option, is it being brought back?

I did this instead in my initializers folder if other people are looking for a solution

```
import Ember from 'ember';
import Notify from 'ember-notify/components/ember-notify';

export var initialize = function(/* container, application */) {
	Notify.reopen({
		messageStyle: 'bootstrap'
	});
};

export default {
  name: 'ember-notify-additional',
  initialize: initialize
};
```

**Comment by btecu** [comment]
It's not necessary anymore.

First of all, current version already registers as a service, so you don't have to do what you're doing.
Second, with current version if you want to use Bootstrap, just use `{{ember-notify messageStyle='bootstrap'}}`.

**Comment by aexmachina** [comment]
That's correct @btecu. @jcope2013 there's instructions in the [CHANGELOG](https://github.com/aexmachina/ember-notify/blob/master/CHANGELOG.md) for upgrading to v3.0.
