### ISSUE TITLE
Request: demo

### ISSUE THREAD

**Issue by lolmaus** [aexmachina/ember-notify#26]
Could you please publish a demo via Github Pages?

**Comment by malchak** [comment]
@lolmaus I just put together the most basic implementation of this addon.  You can clone it here https://github.com/malchak/notify-example, and run it locally.

**Comment by lolmaus** [comment]
Awesome, thank you! There's only one step left: build the demo and push it to the `gh-pages` branch of `malchak/notify-example`.

**Comment by aexmachina** [comment]
Hi there, sorry for the quiet on this issue, been very busy getting a beta release ready. I've nearly finished a project page for this, but I'm moving all my project pages to [my blog](http://aexmachina.info/), and it's not finished yet. Will advise when it's done (hopefully soon).

**Comment by aexmachina** [comment]
I've finally added a project page and demo to my blog: http://aexmachina.info/ember-notify. Enjoy!

**Comment by lolmaus** [comment]
Nice, thank you.
