### ISSUE TITLE
How to not load the styles automatically?

### ISSUE THREAD

**Issue by josemarluedke** [aexmachina/ember-notify#29]
Hi there. 

Is there a way to not automatically load the styles ([vendor/ember-notify.css](https://github.com/aexmachina/ember-notify/blob/master/vendor/ember-notify.css)) so I can make my own? With that I wouldn't need to overtire all the properties that are already defined.

Thanks, J.

**Comment by aexmachina** [comment]
I've just pushed v3.0.12 which adds support for this. You need to specify an option in your Brocfile.js:

```
  var app = new EmberApp({
    emberNotify: {
      importCss: false
    }
  });
```

**Comment by josemarluedke** [comment]
That's awesome! Thank you so much.

**Comment by aexmachina** [comment]
Hey if you feel like sharing your styling I'm thinking about add support for "themes" that provide different ways of presenting the notifications and it'd be good to have another one to start with.
