### ISSUE TITLE
HTMLbars

### ISSUE THREAD

**Issue by gevious** [aexmachina/ember-notify#32]
I run into issues when using this along side Embe 1.10.0 which doesn't have Handlebars

    template must be a function. Did you mean to call Ember.Handlebars.compile("...") or specify templateName instead?

I've narrowed it down to the lib/templates.js file.

**Comment by aexmachina** [comment]
Interesting, okay I can see the issue now. Will look into it. Thanks for the report.

**Comment by aexmachina** [comment]
Strangely, the test suite runs fine on ember 1.10...

**Comment by aexmachina** [comment]
I've just updated ember-cli in ember-notify and added it to a new ember-cli app running ember 1.10.0 and it's working fine for me. Are you sure that your ember-cli is set up correctly for ember 1.10?

**Comment by aexmachina** [comment]
Maybe try the new version 3.0.16, but I'm doubtful that will fix whatever your version is.

**Comment by gevious** [comment]
I've looked at this again and it works with 3.0.16
