### ISSUE TITLE
IE8 Script Timeouts

### ISSUE THREAD

**Issue by csand** [aexmachina/ember-notify#33]
I've been debugging our app for the past few days and finally tracked down the source of several script timeouts + total browser crashes in IE 8 to ember-notify. There's nothing in the README about supported browsers at the moment, so I'm wondering if there's even intent to support IE 8.

Setup:
ember-cli 0.1.12
ember 1.10
ember-notify 3.0.16

**Comment by aexmachina** [comment]
Oh wow, you poor guy!​ Man I'm sorry to hear that. I've never ever run
ember-notify in IE8. Can you please send me a list of the IEs that you've
tried and whether it works or not. Also there's a demo app here that you
can use to test in a vanilla environment:

http://aexmachina.info/assets/ember-demos/#/ember-notify

**Comment by csand** [comment]
Not a problem, just something I wish I'd known about going in. We're currently working on IE 8 and 9 as they're the most prone to errors, but haven't seen any issues with ember-notify in IE 9. The demo app won't even boot in IE 8, but it's 100% fine in IE 9.

**Comment by aexmachina** [comment]
I gotta say, I'm not likely to add support for IE8. I'll update the README
to indicate that IE8 and below are not supported.​

**Comment by csand** [comment]
No worries, I was going to suggest this be closed anyways. Thanks for adding it to the README.
