### ISSUE TITLE
Message Queue

### ISSUE THREAD

**Issue by hhff** [aexmachina/ember-notify#35]
This lib is fantastic!

Is there a way to set it to show messages in a queue, rather than stacking?

Ie for 
```javascript
this.notify.success("It Loaded!");
this.notify.success("So did this");
```
It would act like:
```javascript
Message 1 Appears -> Message 1 Times Out
~then~
Message 2 Appears -> Message 2 Times Out
```

If not - I'd be happy to submit a PR?  Just wanna check to see if it's possible first!

**Comment by aexmachina** [comment]
Those messages return promises which resolve when the message is shown, so you could use that. But there's no event that you could use when they close. You could add a `messageClosed` action to the component and use that. PRs welcome!

**Comment by hhff** [comment]
gnarly, will get to it sometime in the next week or so!

**Comment by hhff** [comment]
Ultimately I just want to be able to use this lib for both standard flash messages + growl style

**Comment by markr79** [comment]
+1

**Comment by btecu** [comment]
Any progress on this?

**Comment by aexmachina** [comment]
Not from me, @hhff?

**Comment by hhff** [comment]
Haha negative unfort- won't get a chance to look at it for sometime
