### ISSUE TITLE
ember-notify without ember cli

### ISSUE THREAD

**Issue by herrherrmann** [aexmachina/ember-notify#37]
Hey there,

I know ember cli is recommended but I'm currently tinkering with a "non-cli" ember 1.10 and would like to try out this notify addon. Is there a pre-compiled version of ember-notify.js for me to import into ember?

Thanks in advance for your help!

**Comment by aexmachina** [comment]
You'll need to use an older version. [v1.2.0](https://github.com/aexmachina/ember-notify/tree/v1.2.0) definitely supports this, but [v2.0](https://github.com/aexmachina/ember-notify/tree/v2.0.0) may also support it as well.

**Comment by herrherrmann** [comment]
Sounds good and thanks for the fast response!
But can you tell me which files from v1.2.0 are necessary for using ember-notify (without cli)? Can I just import ember-addon.js?

**Comment by aexmachina** [comment]
Instructions are [in the README](https://github.com/aexmachina/ember-notify/tree/v1.2.0#module-formats), you'll want one of the build module formats in `dist/` from memory.
