### ISSUE TITLE
Unable to get the css to style the notifications.

### ISSUE THREAD

**Issue by griffind** [aexmachina/ember-notify#38]
For some reason the notification boxes are not being styled by ember-notify.css. All of the notification boxes are grey with black text, regardless of using .success, .warning, etc.

Any ideas?

**Comment by aexmachina** [comment]
It's based on Foundation or Bootstrap styling, so you'll want one of those or roll you own.

**Comment by griffind** [comment]
Okay, that makes sense, thank you for the quick reply. Could you point me in the right direction to style according to whether it is .success or .warning, etc. I'm new to this stuff so thank you for your patience.

**Comment by aexmachina** [comment]
The messages will have CSS classes info, success, warning and alert. You
can use the browser Dev Tools and *Inspect element* to see what it’s
generating.​
​
