### ISSUE TITLE
Style not correct with bootstrap

### ISSUE THREAD

**Issue by brweber2** [aexmachina/ember-notify#40]
In vendor/ember-notify.css:

    .ember-notify {
      /* the following is purely so that it doesn't look broken without Foundation installed */
      box-sizing: border-box;
      background: #ccc;
      padding: 10px;
    }

However, that background causes problems when messageStyle='bootstrap' is used. The gray wins instead of the green, pink, etc.

**Comment by aexmachina** [comment]
Okay thanks, what about if you change that to `border: #ccc;`?

**Comment by brweber2** [comment]
Based on my first test, I think that should work.  I cleared my browser cache before testing, but having someone else verify as well might be a good idea. :)

Thanks!

**Comment by aexmachina** [comment]
This has been done in a recent release. Sorry for not letting you know earlier!
