### ISSUE TITLE
Can I modify the position?

### ISSUE THREAD

**Issue by speed1speed1** [aexmachina/ember-notify#41]
I need a "top center" notify.
Thanks.

**Comment by listepo** [comment]
+1

**Comment by aexmachina** [comment]
You can do this using CSS. Something like this should do the trick:

```
.ember-notify-cn {
  position: absolute;
  top: 0;
  left: 0;
  padding: 0;
}
.ember-notify-cn .ember-notify:first-child {
  margin-top: 0;
}
.ember-notify-cn .ember-notify {
  margin: 10px auto;
}
```

**Comment by listepo** [comment]
Сan add the ability to select in addon?

**Comment by aexmachina** [comment]
I'm open to having several `layoutStyle`s in the addon. Feel free to send one over and I'll add it in.

**Comment by listepo** [comment]
+1

**Comment by KennedyTedesco** [comment]
It would be great an option like that:

```
position: 'top left'
```

Possible values: top left, bottom right etc.

Example:

```
var notify = this.get('notify');
var message = notify.alert('You can control how long it\'s displayed', {
  closeAfter: 10000 // or set to null to disable auto-hiding,
  position: 'top left'
});
```

**Comment by aexmachina** [comment]
Anyone feel like doing a PR for this? I'm not using Ember at the moment, so I'm not the right person to do it.
