### ISSUE TITLE
Writing acceptance tests

### ISSUE THREAD

**Issue by pmdarrow** [aexmachina/ember-notify#45]
I'm having trouble getting my assertions about notifications to pass in my acceptance tests. I followed your instructions on https://github.com/aexmachina/ember-notify/issues/7 to use `then()` and `Ember.run.next()` but the assertions still fail. 

Here's the action on the route that I'm triggering:

```js
actions: {
  save: function() {
    var route = this;
    var record = this.modelFor(this.routeName);
    record.save().then(function() {
      route.notify.success('Item saved.');
      route.transitionTo('home');
    });
  }
}
```

And here's the acceptance test in question:

```js
test('it shows a saved notification', function(assert) {
  visit('/item/1/edit');
  click('#save').then(function() {
    Ember.run.next(this, function() {
      assert.equal(find('.alert-success').length, 1, 'it shows a success message');
    })
  });
});
```

The `'it shows a success message'` assertion always fails. The notification shows up fine during manual testing. Pausing the debugger before `assert.equal()` and looking at the container in Test'em shows that the page is fully rendered but there is no notification displayed. Any ideas? 

I'm using Ember-notify 3.1.4, Ember CLI 0.2.2 and Ember 1.10.0.

**Comment by aexmachina** [comment]
I think you need to use `andThen()`, rather than `click('#save').then()`. This should wait for all promises to resolve before running the `Ember.run.next()`.

**Comment by lan0** [comment]
`andThen()` works for me :+1:

**Comment by aexmachina** [comment]
@pmdarrow is this still an issue for you? FWIW I'd probably just stub out `this.notify` and assert that `this.notify.success` is called - you're not testing notify, you're testing your app code.

**Comment by pmdarrow** [comment]
@aexmachina I think I did try `andThen()` but I'll give it another shot and post my results here.

**Comment by aexmachina** [comment]
Closing this issue, please reopen if necessary.

**Comment by spruce** [comment]
for anybody reading this thread. maybe gonna help to have a constuct like this:
```
andThen(function() {
// wait for everything else to finish
    click('.btn-primary');
    // must use Ember.run because andThen waits till all queues are empty but ember-notify schedules in test scenarios on next run so the queues are never empty
    Ember.run.next(() => { // runs right after didInsert
      assert.equal(find('.alert').length, 1, 'Some message');
      assert.equal(find('.alert-danger span').text().trim(), 'Did not save.', 'display correct message.');
    });
  })
```

**Comment by ohcibi** [comment]
The above approach does not work if there is more going on before the dialog is shown. Also `andThen` to wait for the `click` to finish won't work as it waits for the animation to finish.

@aexmachina could you provide an example on how to test/stub ember-notify properly? I agree that we are not testing notify but our app code. But then again in an acceptance test I'm not testing my implementation but my application, and my application "should show a success alert" *somehow*. So I don't want to test that the application eventually calls `notify` but that it actually shows an alert.

**Comment by aexmachina** [comment]
The way that I do this in the ember-notify tests is to observe the `visible` property. See [this test](https://github.com/aexmachina/ember-notify/blob/master/tests/unit/components/ember-notify-test.js#L33) and in particular the [`observeSequence` function](https://github.com/aexmachina/ember-notify/blob/master/tests/helpers.js#L7).

**Comment by gangware72** [comment]
Hi folks, man in the future here. All this is now irrelevant IMO. The test helper waitFor can take care of this particular issue:
