### ISSUE TITLE
ember-notify 3.2 breaks liquid-fire

### ISSUE THREAD

**Issue by kenips** [aexmachina/ember-notify#49]
I created this bug when I introduced notify into components. Liquid-fire is also dependent on a property named `notify` (see https://github.com/ef4/liquid-fire/search?utf8=%E2%9C%93&q=notify) so this injection breaks its functionality. This is the danger of injection.

I'm opening a bug in place of an MR since the process is too trivial but the new name probably warrants a discussion. We should keep the renamed variable consistent across routes / controllers / components. Thoughts?

**Comment by aexmachina** [comment]
I don't see why the `notify=foo` bindings would be broken by the injection - they should just overwrite the injected property.

For now, users can override the initializer if they want to use a different name for the injection.

What might be a better option for the next release is to remove the injections from the initializer and people can use `Ember.inject.service()` or create their own initializer that calls `EmberNotify.inject(app, 'injectionName`)`

**Comment by anthonycollini** [comment]
I am also receiving this error. When I tried to override the initializer I still couldn't see the flash messages show up. 

I then created a new app with just this addon, and it still does not work properly. As you can see at the sample app, no flash message shows up.

https://github.com/anthonycollini/ember-notify-test

**Comment by aexmachina** [comment]
Hi @anthonycollini, you've exposed a subtle bug. Because you're calling `this.notify.info` in `on('init')`, it's happening before the component has been created. ember-notify has a queue to deal with this case, but it appears that there's a bug in the handling of this case with new versions of ember. I've fixed the problem and pushed v3.2.1.

**Comment by aexmachina** [comment]
In the next major release I'll remove the injection from the initializer and users can use `Ember.inject.service()` instead.

**Comment by knownasilya** [comment]
What's the status on this?

**Comment by aexmachina** [comment]
I switched jobs a couple of months ago and haven't been able to do any open source work. I'll be on holiday week after next, so I'm hoping to do a new version of ember-notify then.

**Comment by Panman8201** [comment]
I haven't used this with liquid-fire just yet, but plan to. With the 4.0.0 release, is this issue resolved as well?

**Comment by aexmachina** [comment]
Could well be. I'm relying on others a bit now because I'm not working in
ember at the moment. Would you like to check?

**Comment by aexmachina** [comment]
This should be resolved in v4.0.0.
