### ISSUE TITLE
Support `SafeString`?

### ISSUE THREAD

**Issue by dasnixon** [aexmachina/ember-notify#62]
Was curious if you would mind me implementing support for `SafeString` being passed to `notify`? I currently have a use case with `ember-i18n`, where the translated property is an object (`SafeString`). However, each time I pass it to `notify` I need to call `.toString()`. Obviously this should be on `ember-i18n`, but I feel like it could be useful.

**Comment by aexmachina** [comment]
Yes that'd be great. Please do!

**Comment by sbounmy** [comment]
Just encountered this today with ember-i18n, would be great aswell ! let me know if I can help :+1:

**Comment by aexmachina** [comment]
Should be pretty simple, I just don't have the time/need so I'm relying on you for PRs!

**Comment by bekzod** [comment]
I think this issue should be closed

**Comment by dasnixon** [comment]
@seven7seven thanks for the implementation!
