### ISSUE TITLE
[Feature Request] configurable positioning/CSS

### ISSUE THREAD

**Issue by efx** [aexmachina/ember-notify#68]
Thanks for making this plugin; it is a lean alternative to other notification plugins in ember addon lands.
I would appreciate being able to configure the CSS included when I install the add on. Right now, I would need to manually override most of the style declarations in `vendor/ember-notify.css`. It would be great to be able to set classes on the `ember-notify` component so that I could have no styling by default and then configure the component to look/animate through custom CSS.

Is this something you would like to add to the plugin? 
If so I can help with a PR.

**Comment by aexmachina** [comment]
Yes I think that's a good idea. I'm not using this module at the moment, so a PR would be preferred.

**Comment by efx** [comment]
merged as of https://github.com/aexmachina/ember-notify/pull/70
