### ISSUE TITLE
Foundation vs 6

### ISSUE THREAD

**Issue by aalasolutions** [aexmachina/ember-notify#71]
I think foundation 6 dont have alert-box now. 

It was not showing any background color for me. I have changed  the following line

```
//node_modules/ember-notify/addon/components/ember-notify.js:64
var classNames = ['button', type]; // it was //var classNames = ['alert-box', type];
```

Colors issue is fixed.

**Comment by aexmachina** [comment]
Cool! Feel like submitting a PR? I'm not using Ember at the moment (doing mobile dev) so I'm relying on the community to keep this module supporting new developments.
