### ISSUE TITLE
Notify messages not showing in tests

### ISSUE THREAD

**Issue by dgavey** [aexmachina/ember-notify#82]
I have an odd problem.  While running my tests I've noticed that the notify alerts aren't showing up at all.  We recently moved from alertify and they were working fine in test mode.

I'm using Ember 1.13.12 and the ember-notify 5.0.3

What's really strange about this, is if I access to dom while the tests are running, I can see that the notify elements are being created and removed so quickly that they don't show up.  So they are being created, they just don't seem to stick around long enough.

Any thoughts as to why this might be?

**Comment by aexmachina** [comment]
Yes, that's intentional. I've added an explanation and workaround [to the README](https://github.com/aexmachina/ember-notify#usage-in-tests).
