### ISSUE TITLE
Not able to test usage of notifications during acceptance tests 

### ISSUE THREAD

**Issue by dennismende** [aexmachina/ember-notify#85]
Hi,

I'm not able to test notifications in my acceptance tests. I imported Notify and set testing to true but it doesn't work.

This is my test:
```
test('submit empty form', function (assert) {

  page
    .visitWithToken()
    .submitEmptyForm();

  andThen(function () {

    assert.equal(page.notifyBoxAmount, 1, 'alert notification is showing up');

  });
});
```
and page.notifyBoxAmount = count('.ember-notify').

My controller function looks like this:

```
confirmUserAccount () {

      if (isEmpty(confirmData.email)) {

        this.get('notify').alert(this.get('i18n').t('error.optin_41').string);

      }
}
```

Does anyone have an idea on this?

**Comment by aexmachina** [comment]
I wouldn't test this using the DOM. I'd set `this.notify.alert()` to a spy and confirm that it's called.

If you're using the DOM then you'll need to wait for the child to be inserted, which may take an extra turn of the event loop.

You shouldn't set `EmberNotify.testing` to true, this is used for its own internal testing. The default behaviour in tests is to run asynchronously, but without any delays.

**Comment by Jordan4jc** [comment]
@aexmachina Would you have an example of using a spy in an acceptance test to test for this? I'm pretty lost and have been searching for hours trying to understand how to do this.

**Comment by aexmachina** [comment]
I’m afraid I’m not using this project at the moment Jordan. ​In an
acceptance test you probably just want to andThen check that the element is
in the DOM, but it’s been a while since I’ve used it. You can set
Notify.testing
= true to disable the delays, see ember-notify-test.js for an example.
​
