### ISSUE TITLE
_emberNotify.default.alert is not a function

### ISSUE THREAD

**Issue by ianbale** [aexmachina/ember-notify#90]
Hi guys,

I've just added this to my ember-cli project. I'm currently on cli v 2.2.0

I'm trying to use this from within a component:

> import Notify from 'ember-notify';
> 
> export default Ember.Component.extend({
> .....
> copyQuestion : function()
> 		{
> 			Notify.alert('Copied question');
> 		},

gives me:
Uncaught TypeError: _emberNotify.default.alert is not a function

I have {{ember-notify messageStyle='bootstrap'}} in my application.hbs

using tis.notify.info("hello")  in a controller gives me several errors including:
Uncaught TypeError: Cannot read property 'info' of undefined

Any idea what might be wrong?

**Comment by aexmachina** [comment]
That's not the correct usage. See the [usage](https://github.com/aexmachina/ember-notify#usage) section of the README.
