### ISSUE TITLE
ember-notify after transition

### ISSUE THREAD

**Issue by jaredgalanis** [aexmachina/ember-notify#91]
I am currently unable to get ember-notify to fire after transitioning routes. Is there a way to fire a notification after a transition to another route has occurred?

I can get a plain JS alert to fire after transitioning:

```this.transitionTo('requisitions.requisition').then(() => {
          alert('This works!');
        }); ```

But not ember-notify:
```this.transitionTo('requisitions.requisition').then(() => {
         this.get('notify').success('This does not work!');
        }); ```

This seems like such an obvious use case I feel like I must be missing something, but I cannot find another open issue like this here, elsewhere or in the documentation. Thanks for any help!

**Comment by aexmachina** [comment]
I can't think of any reason why that wouldn't work. Does notification work in other circumstances?

**Comment by jaredgalanis** [comment]
Apologies, I added {{ember-notify}} to application.hbs and removed it from the many other templates where I was including it and things seem to be functioning as expected now.
