### ISSUE TITLE
Square borders not working

### ISSUE THREAD

**Issue by celicoo** [aexmachina/ember-notify#94]
I would like to use square borders, is it possible? I'm trying set the `radius` to false:

``` javascript
          notify.alert('This one\'s got squared corners.', {
            radius: false
          });
```

Result:

![captura de tela 2016-09-15 as 14 37 17](https://cloud.githubusercontent.com/assets/7903844/18560441/eefe9c02-7b51-11e6-816f-4b067fd3628c.png)

**Comment by aexmachina** [comment]
What [message style](https://github.com/aexmachina/ember-notify#compatibility) are you using? It may be that support for the radius property hasn't been added.
