### ISSUE TITLE
Uncaught TypeError: t.default.String.isHTMLSafe is not a function

### ISSUE THREAD

**Issue by SirZach** [aexmachina/ember-notify#99]
Referring to this line of code: https://github.com/aexmachina/ember-notify/commit/be9018ac82d3de9e7f623f6ae5f6d5f4819d94c6

**Comment by aexmachina** [comment]
What version of Ember are you using?

**Comment by SirZach** [comment]
`2.7.3`

**Comment by aexmachina** [comment]
Cool, thanks. Fixed v5.1.4.

**Comment by SirZach** [comment]
Thanks!
